# Go Linters - GitHub Actions
name: linters
on: [push, pull_request]
jobs:

  # Check linters on latest-ubuntu with default version of Go.
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: "1.17.2"
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install golangci-lint
      run: |
        go version
        curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.8
    - name: Install mockgen
      run: |
        go install github.com/golang/mock/mockgen@v1.5.0    
    - name: Run required linters in .golangci.yml plus hard-coded ones here
      run: make lint
    - name: Run optional linters (not required to pass)
      run: make lint-extra
